apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: kratos-login
build:
  # googleCloudBuild: {}
  local: { useBuildkit: true }
  artifacts:
    - image: eu.gcr.io/mmpt-233505/kratos-login
      docker:
        dockerfile: Dockerfile
profiles:
  - name: local
    activation:
      - command: dev
      - command: run
      - command: deploy
    deploy:
      kubeContext: docker-desktop
      kustomize:
        paths:
          - deploy/overlays/local
  - name: dev
    deploy:
      kubeContext: gke_mmpt-233505_asia-southeast1-a_gke-test
      kustomize:
        paths:
          - deploy/overlays/dev
  - name: prod
    deploy:
      kubeContext: internal
      kustomize:
        paths:
          - deploy/overlays/prod
  - name: staging
    deploy:
      kubeContext: internal
      kustomize:
        paths:
          - "deploy/overlays/staging"
